### ISSUE TITLE
Invalid value of 'authorizationUrl'

### ISSUE THREAD

**Issue by IvanGoncharov** [warehouseman/trello-swagger-generator#2]
Please see this line:
https://github.com/warehouseman/trello-swagger-generator/blob/master/TrelloAPI.json#L24065

**Comment by IvanGoncharov** [comment]
Reported by @darosh here: https://github.com/APIs-guru/api-models/issues/36

**Comment by martinhbramwell** [comment]
If someone has a PR for this I will implement, otherwise I have no time to look at it.
