### ISSUE TITLE
swagger reader fails to parse generated json with some errors

### ISSUE THREAD

**Issue by asfaltboy** [warehouseman/trello-swagger-generator#3]
After running the generator, I get 2 files, a very small TrelloAPI.json and a long editedTrelloAPI.json. The second file looks similar to what you have in the repo. But when I tried any of the JSON files generated in the [online swagger generator][1] it parses partially and returns an error json (see attached below).

[debug.json.zip](https://github.com/warehouseman/trello-swagger-generator/files/587110/debug.json.zip)

[1]: https://generator.swagger.io/#/search

**Comment by martinhbramwell** [comment]
I will open a [gist](https://gist.github.com/) and look at it, but I will not download that file.

Please note that I have not looked at the code for over a year, remember little about it and also believe that Trello has completely altered it's API in the interim.
Finally, you should forget about REST APIs and look to the future : [GraphQL](http://www.apollodata.com/).

**Comment by asfaltboy** [comment]
Thanks @martinhbramwell , I was just toying around with the idea of building a proper python client for trello using an api spec, with e.g swagger or RAML. Not sure how GraphQL can assist me with my issue, kindly elaborate.

Regardless, I'm having too much fun writing a new scraper for their docs, so we can close this issue.

**Comment by martinhbramwell** [comment]
Try [graphql vs rest](https://www.google.ca/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=graphql+vs+rest).

With a REST API you have many round trip calls to the server with little control over the volume of data returned.  With GraphQL, you can assemble queries that return exactly the data your client needs in a single call.

A 3rd party GraphQL gateway service to Trello would be an interesting project, if you're looking to hack something kinda cool.

**Comment by asfaltboy** [comment]
Very interesting, but not my immediate concern TBH. Also I saw [this relevant blog entry](http://graphql.org/blog/rest-api-graphql-wrapper/).

**Comment by IvanGoncharov** [comment]
>  I'm having too much fun writing a new scraper for their docs

@asfaltboy I maintain [collection](https://github.com/APIs-guru/openapi-directory) of Swagger specs for 250+  public APIs.  So I'm very interested in having up to date swagger/RAML spec for Trello API. Can you please share your work on Github?

**Comment by asfaltboy** [comment]
@IvanGoncharov it's still a work in progress.  I have yet to test all the endpoints and I need to add a couple of more properties (permissions and examples). Then it's just mapping the endpoint data to swagger/raml spec format. But I pushed it anyway [asfaltboy/trello-api-spec](https://github.com/asfaltboy/trello-api-spec) just in case anyone wants to contribute 😄
